[build]
builder = "NIXPACKS"

[deploy]
startCommand = "python manage.py migrate && python manage.py collectstatic --noinput && gunicorn item_finder.wsgi:application"

[env]
RAILWAY_ENVIRONMENT = "production"